Add bookings
elGordoGato/java-shareit pull request #2
Opened 2023-08-23 14:32 UTC by elGordoGato

### **Sprint 14**

2023-08-23 20:02 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-23 20:02 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                             @RequestHeader("X-Sharer-User-Id") long bookerId) throws MethodArgumentNotValidException,
`MethodArgumentNotValidException, NoSuchMethodException` Откуда у тебя эти исключения растут?

Не нужно этого всего - что-то ты перемудрил.

2023-08-23 20:02 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User booker = userRepository.findById(bookerId).orElseThrow(() -> new NotFoundException(
Комбинируя код в цепочки лучше переносить каждую новую операцию на новую строку

```
        User booker = userRepository
                .findById(bookerId)
                .orElseThrow(() -> new NotFoundException(
                        String.format("User with id %s not found when trying to book item %s",
                                      bookerId, bookingRequest.getItemId())));
```

2023-08-23 20:02 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            new BadRequestException(item, "item", "Item is not available",
О! Вот это исключение от которого у тебя `throws NoSuchMethodException, MethodArgumentNotValidException` проростает аж до контроллера...

Зачем это всё??
Ну вот же рядом нормальное исключение `NotFoundException` - ничего другого и не требуется...
Почему `BadRequestException` такой особенный?

2023-08-23 20:02 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setStatus(approved ? Status.APPROVED : Status.REJECTED);
Импортируй статики предварительно, код получится короче и читабельнее...

`booking.setStatus(approved ? APPROVED : REJECTED);`

2023-08-23 20:02 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Тут все посъезжало - нужно причесать

2023-08-24 02:34 UTC, elGordoGato commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            new BadRequestException(item, "item", "Item is not available",
Было интересно разобраться как выбрасывать кастомный MethodArgumentNotValidException чтобы не писать новый метод в ErrorHandler, ща перепишу на наследуемый от RuntimeException

2023-08-24 18:34 UTC, FanaticFiz approved these changes

2023-08-28 09:11 UTC, merged