Add item requests
elGordoGato/java-shareit pull request #3
Opened 2023-09-04 10:06 UTC by elGordoGato

### **Sprint 15**

2023-09-04 18:18 UTC, FanaticFiz requested changes
У меня по сути только одна затравочка на подумать/порассуждать ))

2023-09-04 18:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +/*    private void validateDate(LocalDateTime start, LocalDateTime end) {
Уже вторую итерацию висит это закомментированное в коде... может оно таки лишнее? ))

2023-09-04 18:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private User getUser(long id, String operation) {
Заметь ты этот `getUser` ты написал трижды, хотя этот метод есть в сервисе пользователей.
Но он тебе не подходит потому что возвращает DTO.

А может сервисам не возвращать DTO, а возвращать саму ентити User?
Потому что есть и такой подход, может он будет тебе удобнее?

2023-09-05 08:52 UTC, elGordoGato commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +/*    private void validateDate(LocalDateTime start, LocalDateTime end) {
вынес этот код в отдельную ветку, из этой удалил

2023-09-05 09:06 UTC, elGordoGato commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private User getUser(long id, String operation) {
Решил добавить публичный метод `findById` в `UserService` и вызывать его из других сервисов.
Если менять сигнатуру в сервисах на возврат Entity то в каком-нибудь `ItemController` придется проворачивать что-то такое:
>Map<Long, BookingsByItem> bookingMap = getBookingsMap(itemMap);
>Map<Long, List<Comment>> commentMap = getCommentMap(itemMap);
>return getItemDtos(itemMap, bookingMap, commentMap);

Т.е. делать запросы к букинг репозиторию и к комментам, а потом это все мапить в дто - как по мне многовато логики для контроллера, да и довольно объемный рефакторинг, но в целом суть подхода я понял.

2023-09-05 18:30 UTC, FanaticFiz approved these changes

2023-09-07 07:05 UTC, merged