Add docker
elGordoGato/java-shareit pull request #4
Opened 2023-09-07 17:35 UTC by elGordoGato

### **_SPRINT 16_**

2023-09-10 18:29 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-10 18:29 UTC, FanaticFiz commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Давай разберемся с зависимостями...
Какие из них кому нужны. Валидация нужна ли `gateway`?

2023-09-10 18:29 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                      @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Строки не длиннее 120 символов, помнишь?
Перенеси, как то так

```
    @GetMapping("/owner")
    public ResponseEntity<Object> getBookingsForOwner(
            @RequestHeader("X-Sharer-User-Id") long userId,
            @RequestParam(name = "state", defaultValue = "all") String stateParam,
            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
            @Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
        BookingState state = BookingState
                .from(stateParam)
                .orElseThrow(() -> new IllegalArgumentException("Unknown state: " + stateParam));
        log.info("Get booking for owner's items with state {}, userId={}, from={}, size={}",
                 stateParam, userId, from, size);

        return bookingClient.getBookingsForOwner(userId, state, from, size);
    }
```

2023-09-10 18:29 UTC, FanaticFiz commented on server/src/main/resources/application.yml
> +  #config:
подчищаем...

2023-09-11 03:24 UTC, elGordoGato commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Нужна, там же валидируются входные дто, в `server` тоже нужна из-за валидации ентити при обновлении данных.

2023-09-11 03:55 UTC, FanaticFiz approved these changes

2023-11-30 06:16 UTC, merged